global:
  message: Welcome to Order Service Prod Environment...!!!
server:
  port: 8083
message: Hello from Order Prod!
spring:
  datasource:
    url: jdbc:mysql:///order_prod_db
    username: root
    password: root
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
